class PlanningError(Exception):
    """Custom exception for planning-related errors"""

    pass


class AnalysisError(Exception):
    """Custom exception for analysis-related errors"""

    pass
